### ISSUE TITLE
No Sample Basket on BCM community "Sample Comparison" view

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#1]
On QA server, BCM configuration

The Sample Comparison View hides the Sample Basket and fails to populate with data from the selected samples.  Example [URL](https://qa.genialis.com/bcm/visual_analysis?_b=bc21bf57-37af-432f-89cf-b7b101d43e30)
![bcm lacking basket](https://cloud.githubusercontent.com/assets/1234176/24925308/709313a6-1ebd-11e7-9a10-534d7f32772f.jpg)

Whereas on the Universe configuration (or Lexogen, presumably others too) the Sample Basket is present for this View, as it should be. [URL](https://qa.genialis.com/universe/visual_analysis?_b=2f11fcdf-7e0b-44bf-b26f-b0263be901fd)

![universe with basket](https://cloud.githubusercontent.com/assets/1234176/24925321/78ab6048-1ebd-11e7-8693-dc5c69183f4e.jpg)

**Comment by mstajdohar** [comment]
@jkokosar, please review.

**Comment by mstajdohar** [comment]
Could @JenkoB help?

**Comment by JenkoB** [comment]
Fixed.

**Comment by mstajdohar** [comment]
@rafecooks please test then close the issue if it works.

**Comment by rafecooks** [comment]
Fixed.
