### ISSUE TITLE
Volcano plot -log10(FDR) default and limits

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#14]
Server: QA
Community: rna-seq
User: admin

On the Volcano plot, the FDR threshold default = 0.05, and thus the default -log10(FDR) threshold is 1.3. However, this shows up as -1.3.
![screen shot 2017-04-18 at 9 54 25 pm](https://cloud.githubusercontent.com/assets/1234176/25161466/bbb3fe8a-2481-11e7-9417-7b5c29133ce0.jpg)

As soon as I start tinkering manually with the thresholds, the negative sign disappears and all seems right with the world. 
![screen shot 2017-04-18 at 9 55 16 pm](https://cloud.githubusercontent.com/assets/1234176/25161488/d8cbeea6-2481-11e7-8468-4f4ab198a063.jpg)
![screen shot 2017-04-18 at 9 55 09 pm](https://cloud.githubusercontent.com/assets/1234176/25161487/d8c9868e-2481-11e7-8c5c-78b08d1de67d.jpg)

However, when I click "RESET" the negative sign returns
![screen shot 2017-04-18 at 9 55 49 pm](https://cloud.githubusercontent.com/assets/1234176/25161499/e586f014-2481-11e7-936d-fa640aa4f65b.jpg)

Also, the FDR threshold line behaves inconsistently above FDR = 1e-14, -log10(FDR) = 14. If the user manually changes the -log value greater than 14, the threshold line goes to the top of chart. 
![screen shot 2017-04-18 at 9 58 54 pm](https://cloud.githubusercontent.com/assets/1234176/25161622/c160bbba-2482-11e7-8925-81c4d09e2c72.jpg)

![screen shot 2017-04-18 at 9 59 36 pm](https://cloud.githubusercontent.com/assets/1234176/25161625/c459fd40-2482-11e7-8ba5-d63707e6c64a.jpg)

However, if the user changes the FDR value to, say, 1e-15, the -log value behaves as does the threshold line.
![screen shot 2017-04-18 at 10 00 11 pm](https://cloud.githubusercontent.com/assets/1234176/25161633/ccc4f4da-2482-11e7-81d5-4b996dadf1c0.jpg)

Perhaps we can simply set a limit at FDR = 1e-14, or even at 1e-5. No one should ever concern themselves with that many decimal points.

**Comment by rafecooks** [comment]
By thew way, I do not consider this bug a high priority. No one should fuck with that many decimals

**Comment by mstajdohar** [comment]
@lukaw3d Was this fixed?

**Comment by lukaw3d** [comment]
Yes. it was fixed
