### ISSUE TITLE
Schema permissions for Recipes page on BCM deploy

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#17]
Server: BCM
Community: RNA-seq
User: demo

Logging into bcm.genialis.com/rna-seq/ (user = demo, pwd = demo1234), received this schema error:

![screen shot 2017-04-20 at 1 46 27 pm](https://cloud.githubusercontent.com/assets/1234176/25247547/ba5d5a22-25d0-11e7-99dc-c4a0c83ac3b0.jpg)

**Comment by mstajdohar** [comment]
@JenkoB Is this fixed?

**Comment by JenkoB** [comment]
Yes, I gave permissions for BCM and linlab group.
