### ISSUE TITLE
Avoid showing duplicate samples in Sample Basket

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#2]
QA server, Lexogen configuration [URL](https://qa.genialis.com/lexogen/visual_analysis?_b=c876bbb3-d8f6-4cf5-9a64-7453b94e4ad6)

I added 6 samples to the basket. Then added 4 others. Then did a search that produced the same 10, and I selected these 10 and added them to the basket.
![dups in the basket](https://cloud.githubusercontent.com/assets/1234176/24925872/4650855e-1ebf-11e7-86b6-94f33d546e1b.jpg)

The basket should not show redundant samples. Meanwhile, on the plus side, the visualizations seem to only respond to one copy of the samples.

**Comment by kostko** [comment]
> The basket should not show redundant samples.

Hm, but samples are grouped under "breadcrumbs". What you are saying would make sense if there was no grouping and the basket would be a flat list. But since there are breadcrumbs I don't think this is so clear-cut.

**Comment by rafecooks** [comment]
Let's do this. Archive, delete, or pause the bug report. Let's get more user feed back (I have begun producing recorded videos of users on the app) and see if this is helpful or hurtful.

Another solution (that is buried on the backlog) that might be helpful is to create a visual indication in the Search Results table when a sample has already been added to the Sample Basket.
