### ISSUE TITLE
Hide collections without permissions

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#20]
Server: BCM
Community: rna-seq
User: Demo

https://bcm.genialis.com/rna-seq/bioinformatics?_b=

Issue: 
I am able to see tons of collections; very cluttered; most are not mine. When I click on one that was created by someone else, e.g. Rachel, I can enter the collection but I see no data.

Example:
Too much clutter—
![collections](https://cloud.githubusercontent.com/assets/1234176/25869166/f8050188-34c4-11e7-8aa0-f82c4150fc21.jpg)

Click on the first collection (owned by Rachel), nothing inside—
![nothing to see](https://cloud.githubusercontent.com/assets/1234176/25869177/0ab1c6f4-34c5-11e7-8d16-be8177434fde.jpg)

Preferred behavior:
Within the bioinformatics dashboard, a user should only see collections to which he or she has permissions to see the data. Otherwise there is too much clutter, and confusion when entering someone else's collection but no data populates.

**Comment by dblenkus** [comment]
`Demo` user is in `BCM` and `linlab` groups. First is used to grant permissions to users and second is used to share date in Charles's lab. This is probably why you see all of those collections.

I've removed your user from `linlab` group. Please test again and let me know if it works as you expect.

**Comment by rafecooks** [comment]
I still see lots of Rachel's Collections. But this was actually a complaint originating with Charles. Even logged in as `linlabdemo`, he was frustrated that he could see all these collections, but when he clicked into them, he couldn't see any data.

Perhaps this is more of a UX issue— what should people in a group see, versus what can they access?

**Comment by rafecooks** [comment]
Maybe rather than treat this as a bug and changing the permissions scheme, we think instead about creating a new feature: subsections such as:
- "My collections"
- "Group collections"
- "Public collections"

With collapsable panels like a Gmail inbox. I'll have Andraz create some mockups

**Comment by mstajdohar** [comment]
Consider using a Filter panes for switching between "My collections", "Group collections" and "Public collections", with "My collections" checked by default. The filter panel would fit good in the Collection Search as well, giving a consistent UX.

**Comment by mstajdohar** [comment]
@rafecooks Please close this issue when you include the suggested improvements into a PRD or a spec.

**Comment by andr47p** [comment]
Hi, I agree with @mstajdohar that filter should be used.

* **default filter when you open the page** could be user's name (perhaps they can even set their own default filters - maybe by double clicking on the filter word/phrase could make it "permanent".

* **but only when multiple filters at once are available** (so the filter function is still usable for additional searches besides already by-username-filtered list)
