### ISSUE TITLE
Fix Cuffnorm data accessibility

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#21]
# Cuffnorm data accessibility
- Within the Bioinformatics Dashboard (BD)/ Collection Details for `p4936_ms2_rna` 
- Charles selected Cuffnorm data object
- The issue is that most of the files Charles wants to access are buried in the Zipped folder (R_data.zip) in the outputs.
![screen shot 2017-05-09 at 3 35 10 pm](https://cloud.githubusercontent.com/assets/1234176/25872478/8711ee58-34d0-11e7-89f6-4613e468b786.jpg)

- The most important of these are `cuffnorm_all_fpkm_exprs_norm.txt` and `cuffnorm_all_fpkm_exprs_raw.txt`, which should be made accessible in the outputs table. Furthermore, the `cuffnorm_all_fpkm_exprs_norm.txt`  data **should be the expressions used in the Visualizations**. If not, that needs to be **_corrected_**.
![screen shot 2017-05-09 at 4 00 57 pm](https://cloud.githubusercontent.com/assets/1234176/25872533/c1508b10-34d0-11e7-80fa-2874c32ecd6d.jpg)

- The R_data.zip contains 70 files. 60 of these are pairwise comparisons of some sort that contain the substring "vs" in the title. These belong zipped. The other 10 are .txt, .png or .pdf files that may be better presented in the Outputs table.
![screen shot 2017-05-09 at 4 00 23 pm](https://cloud.githubusercontent.com/assets/1234176/25872537/c4d8f31c-34d0-11e7-8bf2-cf55ac7fa951.jpg)

**Comment by rafecooks** [comment]
While we're tinkering with the R output, we should see if we can re-label the boxplot to samples, rather than the `X370_1` type IDs

**Comment by dblenkus** [comment]
I think that the problem is that only `X370` part is passed to the process and `_1` is auto-generated. So this means that labels have to be relation-specific and, as relations don't have names, only option is to use `id` or something similar.

@jkokosar can we pass specific label for each sample to the process?

**Comment by mstajdohar** [comment]
> While we're tinkering with the R output, we should see if we can re-label the boxplot to samples, rather than the X370_1 type IDs

Reported in https://github.com/genialis/resolwe-bio/issues/266.
