### ISSUE TITLE
Terms of Service need to link to privacy policy

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#22]
Update **Terms of Use** to the following file contents: https://drive.google.com/open?id=0B0veuqdivM_DUXEyRFJuTThyTzA

Hyperlink to the Privacy Policy. https://drive.google.com/open?id=0B0veuqdivM_DR0ZLenRMbHFidVk

Please note, the Privacy Policy has a placeholder for a reciprocal link back to the Terms of Use.

Also, we must have the most recent update **DATE** visible at the top of both documents.

**Comment by mstajdohar** [comment]
Update the notice on the registration page from "By creating an account I agree to the Terms and Conditions" to "By creating an account I agree to the Terms and Conditions and Privacy Policy". 

Include links to Terms and Conditions and Privacy Policy in the top right user menu. This is not the best placeholder for this kinds of information, but it will do until we have a footer (cc @andr47p). At least Terms and Conditions and Privacy Policy will be accessible from the app directly.

**Comment by hadalin** [comment]
@rafecooks In the app it says _Terms of Service_, but here it's _Terms of user_. Which one should we use?

**Comment by rafecooks** [comment]
http://www.termsandconditionsesq.com/term-service-use-conditions/

There is no functional difference so let's pick one and we'll be consistent. 

I prefer "Terms of Use." This means replacing "Terms of Service" and "Terms and Conditions" everywhere we see them.

@andr47p Please help us find each example where these show up and keep us consistent with **Terms of Use**

**Comment by andr47p** [comment]
@rafecooks Help you find pages that contain those words?
As far as I can see only on:
> 
> https://qa.genialis.com/universe/user/create_account?_b=
> https://qa.genialis.com/universe/tos?_b=

As for the temporary placeholder in the menu: (highlighted version if you want it more prominent)
![tos](https://cloud.githubusercontent.com/assets/27995417/26151870/ee39fb40-3b04-11e7-85e1-fce553b31823.jpg)

**Comment by hadalin** [comment]
Maybe just `Terms of use` instead of `View Terms of Use`? @rafecooks

**Comment by rafecooks** [comment]
Agreed. No need to include "View"

**Comment by hadalin** [comment]
For future reference

>Please help us find each example where these show up and keep us consistent with Terms of Use

It's easier for me to search where certain things show up in the app, because I can search through the code. Sometimes things are hidden because the app is configured in such a way and can't be accessed at all.

**Comment by rafecooks** [comment]
thanks!

**Comment by hadalin** [comment]
Is this ordering for signed in user ok or should `Sign out` be the last one?

![screen shot 2017-05-17 at 16 59 05](https://cloud.githubusercontent.com/assets/1746370/26160669/38428b72-3b22-11e7-9ca5-977417e3288f.png)

**Comment by hadalin** [comment]
I'd rather put `Sing out` last.

**Comment by hadalin** [comment]
Never mind, I already switched 😄

**Comment by rafecooks** [comment]
Yeah, last is good. thanks

**Comment by mstajdohar** [comment]
Can you insert a horizontal line between Sign out and Terms of Use? I'd like to see how that looks like.

**Comment by andr47p** [comment]
![sign_out](https://cloud.githubusercontent.com/assets/27995417/26190213/84fef8f2-3ba8-11e7-9fdc-cfdfeecc18bd.png)

VS

![sign_out2](https://cloud.githubusercontent.com/assets/27995417/26190285/edc79b32-3ba8-11e7-9b8b-be04260c17ac.png)

**Comment by hadalin** [comment]
<img width="283" alt="screen shot 2017-05-18 at 12 01 53" src="https://cloud.githubusercontent.com/assets/1746370/26197239/cd2020ac-3bc1-11e7-8ecf-b2e21f353ee6.png">

**Comment by hadalin** [comment]
Currently

<img width="317" alt="screen shot 2017-05-18 at 12 04 32" src="https://cloud.githubusercontent.com/assets/1746370/26197345/2ff8dab6-3bc2-11e7-9b40-1a9f4cd4371d.png">

**Comment by hadalin** [comment]
Which one should I use?

**Comment by mstajdohar** [comment]
@andr47p, @rafecooks what would you suggest?

**Comment by rafecooks** [comment]
My favorite:

Sign Out
______
ToU
Privacy

where the line does not reach the edges of the box but rather indented a bit

**Comment by andr47p** [comment]
Well I prefer "sign out" at the bottom (since I expect this option at the bottom and it's easier to quickly select the last as opposed to something in the middle), but really it's not problematic either way.

**Comment by rafecooks** [comment]
On second thought, I've reviewed a bunch of different apps I'm signed in to, they all have it at the bottom. Let's go with Andraz's preference. 

ToU
PP
-----
Signout

**Comment by mstajdohar** [comment]
But they do not have the ToU/PP above the Sign out, right? They have them in the footer.

**Comment by hadalin** [comment]
What about the menu for the unauthorized user?

<img width="248" alt="screen shot 2017-05-18 at 13 02 38" src="https://cloud.githubusercontent.com/assets/1746370/26199448/4fbd60f8-3bca-11e7-9e76-8db6d60f20db.png">

**Comment by rafecooks** [comment]
Right. But we don't have a footer. Should we design and implement a footer? How long will that take? Should we put them in the drop down in the meantime?
![screen shot 2017-05-18 at 6 02 15 am](https://cloud.githubusercontent.com/assets/1234176/26199482/c161f86c-3b8f-11e7-8887-7b0ebfb0c249.jpg)

**Comment by mstajdohar** [comment]
I have proposed to pot this in the user dropdown, because we do not have a footer. We will move the links to the footer when we add the footer, but let's not wait for that.

**Comment by rafecooks** [comment]
Agreed. So for now, dropdown:

ToU
PP

----

Sign Out


Then footer in time.

**Comment by hadalin** [comment]
It's inconsistent with https://github.com/genialis/bug-reports/issues/22#issuecomment-302372710

How about two dividers?

So now it's

<img width="265" alt="screen shot 2017-05-18 at 13 29 27" src="https://cloud.githubusercontent.com/assets/1746370/26200392/265e282e-3bce-11e7-8a9f-5ebb9636b5eb.png">
<img width="250" alt="screen shot 2017-05-18 at 13 29 44" src="https://cloud.githubusercontent.com/assets/1746370/26200391/265d2fa0-3bce-11e7-9e65-fe5466591774.png">

**Comment by andr47p** [comment]
IMO:

(signed out menu)

```
Sign in
Create Account
Terms of Use
Privacy Policy
```

(signed in menu)

```
Edit Profile
Change Password
Terms of Use
Privacy Policy
------------------
Sign Out
```

This way we have "Sign in" -> "Edit Profile" in first position and "Sign Out" at bottom.

**Comment by hadalin** [comment]
So what's the final verdict on this?

**Comment by mstajdohar** [comment]
Follow @andr47p latest suggestion.
