### ISSUE TITLE
Cannot see gene sets/ venn diagrams set as public

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#24]
Server: app
Community: rna-seq
User: (regular)

As Admin I created two gene sets and a venn diagram:

- (GS) edgeR_Upreg149
- (GS) DEseq_upreg60
- (Venn) DESeq-edgeR-Upreg-demo

Domen then made these public, so that any regular user on the app could see these data and play with them. But for some reason they do not show up. 

@dblenkus Can describe more what he did in terms of permissions. He suggests this may be a bug in elastic search.
@kostko ???

**Comment by dblenkus** [comment]
`public_permission` field should be added to the [`BaseDocument` class](https://github.com/genialis/resolwe/blob/master/resolwe/elastic/indices.py#L58), populated at the end of the `process_object` function and  `filter_permissions` function in `ElasticSearchMixin` viewset should consider it.

**Comment by mstajdohar** [comment]
Who work on the public permissions bug, @dblenkus or @kostko? Can you set a group permission as a workaround, would that work?

**Comment by dblenkus** [comment]
This should be fixed here: https://github.com/genialis/resolwe/pull/285

**Comment by mstajdohar** [comment]
Awesome
