### ISSUE TITLE
Genus species names need to be consistent in spelling and capitalization

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#25]
Server: BCM
Config: rna-seq
User: any (Demo, Rachel)

The dropdown card for the recipes lists the available species with both Genus and Species name capitalized. E.g. Homo Sapiens.

This should be _**H**omo **s**apiens_

And true for all organisms, first word Cap, second word lower

![screen shot 2017-05-17 at 10 26 46 am](https://cloud.githubusercontent.com/assets/1234176/26162188/ae33880e-3aeb-11e7-8a29-4e220c1d9e81.jpg)

**Comment by rafecooks** [comment]
I am not sure whether this issue exists elsewhere. In general, we need to be 100% consistent with spelling and caps for the organism and source info

**Comment by mzganec** [comment]
Fixed and merged with master. Closing.
