### ISSUE TITLE
/Dicty/ configuration recipes not RNAseq

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#28]
Server: BCM
Config: dicty
User: Admin

The second bullet in the recipes card says "Upload RNA Seq reads", but this workflow does not use RNA-seq. It is a DNA-seq workflow. The bullet should say simply "Upload reads"
![screen shot 2017-05-17 at 11 37 44 am](https://cloud.githubusercontent.com/assets/1234176/26165437/958c47dc-3af5-11e7-945f-363150b42449.jpg)

**Comment by rafecooks** [comment]
Also, I would change the title from "Chemical mutagenesis - Align Reads" to "Chemical mutagenesis variant detection"

I know this step only does the alignment, but the title is clunky as is

**Comment by mstajdohar** [comment]
I think both titles can be configured to arbitrary text in configuration. @jvrakor please configure the UI. @jkokosar please advise.

**Comment by jvrakor** [comment]
The issue is resolved. I also used title case in titles as that was inconsistent before. We can use sentence case if preferred.   
![screenshot from 2017-05-18 09-41-39](https://cloud.githubusercontent.com/assets/26652775/26191504/6aa8ba82-3bae-11e7-8d10-34c732b599dc.png)

**Comment by rafecooks** [comment]
This is great. Thanks for catching the caps consistency. What you show in the screen shot is "Sentence case" which, in my opinion, is absolutely the correct choice.
