### ISSUE TITLE
Upload and Export action buttons not responsive in Bioinformatics Dashboard

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#29]
Server: BCM
Config: dicty
User: Admin

I cannot export selected files, nor upload new data, using the action buttons.
![screen shot 2017-05-17 at 12 10 10 pm](https://cloud.githubusercontent.com/assets/1234176/26166690/edda786a-3af9-11e7-9780-912190afd1a0.jpg)

**Comment by rafecooks** [comment]
Nothing happens when I click the export button

**Comment by mstajdohar** [comment]
@hadalin Please hide the Export and Import buttons in all tables, because they are not supported on the new platform.
