### ISSUE TITLE
Alphanumeric sorting of sample names on bar graphs

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#3]
QA server, Lexogen community, [URL](https://qa.genialis.com/lexogen/visual_analysis?_b=4376a211-96ea-458f-bc34-6acde1c3d24b)

We need to arrange the samples on the X-axis of the bar graph (Gene Expression view) in alphabetical order. In the future we might dream of supporting a forced order, or a ranked order, or something. But for now, at the very least, the sample names need to be sorted.

In the following example, all the tall bars belong to the A1,A2,A3 samples. Yet the bars do not group together on the X-axis. Thus a user needs to hover over each and every bar to attempt to discern a signal.
![sort samples on bar graph](https://cloud.githubusercontent.com/assets/1234176/24926439/30bb175c-1ec1-11e7-8ec8-8d5c0ad02a09.jpg)

**Comment by mstajdohar** [comment]
@lukaw3d Have you done this yet in your recent batch of fixes?

**Comment by lukaw3d** [comment]
Yes
