### ISSUE TITLE
Hide sample basket in Search if no visualizations

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#33]
# Issue 2
Tool tip on Search icon on the left navigation bar should say `Search and View Results`
This should be changed globally so all configurations are consistent.

# Issue 3
The Swift use case does not have visualizations, but displays a sample basket. I am not sure what to do with the sample basket and the `add to sample basket` (+) icon on the Results table.

Option 1. Just leave it, because they will have a Visualizations page in a few weeks... 
Option 2. Inactivate sample basket (a la Rochester) and remove (+) icon, which I suspect would take a lot of work.

Could someone (@hadalin or @lukaw3d) comment on how hard option 2 would be? I am inclined to leave it alone since we are still dealing only with Swift's internal testers.

**Comment by rafecooks** [comment]
@mstajdohar

**Comment by mstajdohar** [comment]
* Issue 1: I have fixed the description text. The style bug report is already here: https://github.com/genialis/genialis-apps/issues/577
* I have refactored the second and third issue and assigned to @hadalin.

**Comment by mstajdohar** [comment]
Low priority.

**Comment by hadalin** [comment]
Option 2 is not hard actually. You basically just check if visualizations are enabled (visible) in configuration and show/hide basket/add-to-basket-button.

**Comment by rafecooks** [comment]
I have discussed with Miha. I would actually prefer to leave these features in place because Swift is eager for the Visualizations and this will give them the impression the Viz are coming. Whomever configures Swift after the re-deploy, please ensure the Viz icon is **present** in the navigation bar. We want to whet their appetites.

**Comment by rafecooks** [comment]
Leave the basket and (+) icon for Swift. Visualizations coming soon. Also, on configuration after redeploy, please make sure Viz icon is present in navigation bar.

**Comment by hadalin** [comment]
>Tool tip on Search icon on the left navigation bar should say Search and View Results

This is fixed.

**Comment by hadalin** [comment]
If there's nothing else to do I propose we close this issue.
