### ISSUE TITLE
Gene Sets module, Heat Map View, too crunched

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#37]
App
RNAseq
Rafael+3 (or Admin)
[URL](https://app.genialis.com/rna-seq/visual_analysis?_b=d6d93580-d6e5-4e8c-bcb1-f8b69f20fbc2&_s=a1c704d1-8011-408a-930b-13064329fc43)

The Gene Sets Module on the Heatmap View is crunched to the point of being useless at default resolution: 
![screen shot 2017-06-02 at 1 17 20 pm](https://cloud.githubusercontent.com/assets/1234176/26739039/fb826286-4795-11e7-9b2f-b8561486e398.jpg)

Looks ok at high resolution:
![screen shot 2017-06-02 at 1 19 09 pm](https://cloud.githubusercontent.com/assets/1234176/26739074/186ca3fc-4796-11e7-9a39-2ecbc0fcd7de.jpg)

**Proposed solutions**
- Remove DE objects from this table? Users can create their own DE gene lists from the Volcano Plot. That way the `Number` column won't be nearly so wide. (Note: will this fuck up Rochester?)
- Remove `Type` column? No users thus far have intuitively understood what `DE`, `GS`, `VD` mean.
- Arrange columns in such a way that `name` is preserved in width and the other columns are crunched instead?
- Make columns resizable?
- Fix pagination spacing at bottom of card
- Magnifying glass icon is poorly aligned with Filter box... this could wait, because we are soon changing the icon for Filter... or fixed now and changed later.

**Comment by lukaw3d** [comment]
Another possible solution:
* Redistribute cards layout

**Comment by mstajdohar** [comment]
I would remove the type column for start.

**Comment by mstajdohar** [comment]
Can we define a minimum width for the name column?

**Comment by mstajdohar** [comment]
Crunch the number column if too wide and display the tooltip with all information about the number of expressed genes.

**Comment by mstajdohar** [comment]
Get rid of the eye icon by making the names clickable. @andr47p Are you OK with this?

**Comment by andr47p** [comment]
I'm not OK with this (removing "inspector" icon) because:
* inconsistent with (at least) results in search pages
* there is a) no visual cue the name is clickable and b) we already use "colored" text to display downloadable links so highlighting the name is not a good choice...

**Comment by hadalin** [comment]
>inconsistent with (at least) results in search pages
search page table doesn't have eye icon

>we already use "colored" text to display downloadable links so highlighting the name is not a good choice
search page table has colored clickable name

Or am I missing something?

**Comment by andr47p** [comment]
I was referring to this "search (& results)" page: https://drive.google.com/open?id=0B6WDEN-S9RbfN2JPUXByLWVxQzA

**Comment by hadalin** [comment]
Me too, but following Rafe's instructions

![screen shot 2017-06-05 at 14 54 32](https://cloud.githubusercontent.com/assets/1746370/26784645/08e18c48-49ff-11e7-9e4a-ef1d37a124ee.png)

there's no eye icon and the name is clickable.

**Comment by rafecooks** [comment]
@hadalin In what stage of the review process are the fixes for this issue? Just curious.

**Comment by hadalin** [comment]
Not in review, still in queue.

**Comment by hadalin** [comment]
Queue as in still waiting for implementation.

**Comment by rafecooks** [comment]
ok, thanks

**Comment by hadalin** [comment]
@rafecooks https://github.com/genialis/genialis-apps/pull/619#issuecomment-310595394
