### ISSUE TITLE
Search has limited ability to find partial strings

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#4]
QA server, BCM community

Priority 1: the desired behavior is to identify Samples by searching over any substring within the Sample name. 
Priority 2: the search should also consider any field (e.g. column) that is visible from the interface— thus all columns should be searchable. 

A few examples of failure:

Search for "FDA"
Expect: 9 results based in the substring "FDA" present at various places in Sample names, separated by underscore "_"
Actual: 0 results
![fda](https://cloud.githubusercontent.com/assets/1234176/24966708/5c246018-1f6d-11e7-9da6-5dc92e3fa2ce.png)

Search for "test"
Expect: 5 results based in the substring "test" present at various places in Sample names, either separated by underscore "_", or by white space, or adjacent to other text (e.g. "test1")
Actual: 1 result: separated by white space
![test](https://cloud.githubusercontent.com/assets/1234176/24966819/a3f7fe86-1f6d-11e7-87e9-b8fa66e5bce8.png)

Search for "REV"
Expect: 8 results based in the substring "REV" present at the beginning of Sample names, preceding an underscore "_"
Actual: 6 results. However, I suspect the six samples returned by the search were identified by the presence of "REV" in some other descriptor, but not Sample name.
![rev](https://cloud.githubusercontent.com/assets/1234176/24966943/054482d6-1f6e-11e7-8e5b-ef67a81a8a3b.png)

Search for "demo"
Expect: 11 results based in the substring "demo" present either n Sample name or in the contributor column.
Actual: 0 results.
![demo](https://cloud.githubusercontent.com/assets/1234176/24967000/35aeed4e-1f6e-11e7-83f5-69176361d19b.png)

**Comment by kostko** [comment]
>  by searching over any substring within

Can you be more specific about "any substring"? In your examples, does this mean that you would like to be able to search for "FDA" in "REV_FDA_A2" or also to search for "FD" in "REV_FDA_A2" or even "DA" in "REV_FDA_A2"?

**Comment by rafecooks** [comment]
My instinct is to make this as generic as possible. Biologists are famously obnoxious about naming samples. A typical sample name has a lot of technical short-hand embedded in the string. So we would want to allow them to search for any substring such that they could pick out even 2-character terms. More conceptually, I am hesitant to impose search rules (e.g. search must be > 3 characters; or search must be text at beginning of string) unless we somehow make these rules obvious to the end user.

Here's an example:
![screen shot 2017-04-13 at 5 16 43 am](https://cloud.githubusercontent.com/assets/1234176/25000943/c9e935e2-2008-11e7-8fd0-3c360434c538.jpg)

Imagine a user wants to find all the samples with "HD" rather than "NA" in the second block of text.
Or, a user wants to find all those with "65" at the end.

I am open to discussing why this might be a bad idea or hard to implement.

**Comment by kostko** [comment]
The three cases I mentioned require completely different implementations:
* The first case simply requires tokenzing on all non-word characters (e.g. to include `_`).
* The second case in addition requires building a special n-gram prefix index. This increases the size of the index by a lot, since all the prefixes need to be generated and indexed for each token (e.g. a token consisting of _n_ characters requires all _n_ prefixes to be indexed).
* The third case (searching for arbitrary substrings in arbitrary places) is very hard to support _efficiently_ and I think it should be avoided.

**Comment by rafecooks** [comment]
Ok, I see. Well absolutely tokenize all non-words. I am concerned about cases like searching for "test" when the names include "test1" or "test6" (see earlier example). But we can also be lean about this and fix the easy, obvious bit and wait to see how many users have problems with the partial text issues...

**Comment by rafecooks** [comment]
So if the text is "00hr" the tokens would be ["00", "hr"]?

I think this will solve most cases.

**Comment by kostko** [comment]
Pushed PRs (genialis-base and resolwe) with proposed improvements.

**Comment by mstajdohar** [comment]
Does this change only affect the name field? So that the values in the other fields like description and descriptors do not get tokenized.

**Comment by kostko** [comment]
> Does this fix only affect the name field? So that the values in the other fields like description and descriptors do not get tokenized.

We use this tokenizer for the following fields: `slug`, `name`, `descriptor_data` (this is data derived from sample and data descriptors).

**Comment by mstajdohar** [comment]
This is great.

**Comment by kostko** [comment]
But `description` uses the default tokenizer, which is more suitable for standard text. Is this ok or should we change that as well?

**Comment by mstajdohar** [comment]
Let's keep the default tokenizer and test the fix first.
