### ISSUE TITLE
Sample Clustering modules sometimes render and sometimes don't

### ISSUE THREAD

**Issue by rafecooks** [genialis/bug-reports#45]
As seen in today's Jam Session:

Server: app
Community: rna-seq
User: Admin
Dataset: Search for “159”, select all 20 samples

Sample Comparison View, [URL](https://app.genialis.com/rna-seq/visual_analysis?_b=1bd8db84-18e8-4fb3-a8da-669e9b71b854&_s=7f5e9ef5-a355-444d-b4fe-0c0871d9089c)

- PCA loaded in 5 seconds; after 30 seconds with no HC, I refreshed the page. 
- HC loaded immediately but no PCA after 30 seconds. 
- I refreshed the page again and both appeared within 4 seconds.

Desired behavior: both modules render 1st time, quickly (e.g. less than 5 seconds)

This issue does not always happen. Not sure what causes it and why.

**Comment by mstajdohar** [comment]
@kostko, @dblenkus, @lukaw3d It seams that sometimes we do not get the response at all. For example, you can wait forever with a spinning progress wheel in the HC module. After the refresh however, the results load instantly. Ideas?

**Comment by kostko** [comment]
Can this be reproduced also on latest qa2 deploy?

**Comment by rafecooks** [comment]
Seems fixed. Will close until we hit further errors
