### ISSUE TITLE
Old version of UI is used after deployment of the server

### ISSUE THREAD

**Issue by dblenkus** [genialis/bug-reports#7]
Looks like `index.html` is cached to heavily and the only option to get the new version of the UI is to hard refresh the page.

Caching should be completely disabled for `index.html` (and probably `apps.config`) in nginx configuration.

**Comment by mstajdohar** [comment]
@tjanez Have you disabled the caching of `index.html` and `apps.config`?

**Comment by tjanez** [comment]
> @tjanez Have you disabled the caching of index.html and apps.config?

I've fixed this today: https://github.com/genialis/tower/commit/f3a551c09fe122b79f3a72fe6b32f6c691e67244.

I've deployed this to the QA2 server and it appears to work.

- Before deployment of the fix:
  ```bash
  $ curl -s -X GET -I https://qa2.genialis.com/index.html | grep Cache-Control
  $ curl -s -X GET -I https://qa2.genialis.com/apps.conf.js | grep Cache-Control
  $
  ```

- After deployment of the fix:
  ```bash
  $ curl -s -X GET -I https://qa2.genialis.com/index.html | grep Cache-Control
  Cache-Control: no-cache
  $ curl -s -X GET -I https://qa2.genialis.com/apps.conf.js | grep Cache-Control
  Cache-Control: no-cache
  $
  ```

If you encounter any more issue, please re-open or file a new bug report.
